# This sets up an environment to test the remote dotfiles installer as you
# would on a fresh Arch installation.

FROM archlinux:base

# Install minimal dependencies needed for my dotfiles.
RUN pacman -Syu --noconfirm git python sudo openssh curl

# Create a non-root test user with passwordless sudo
RUN useradd -m -s /bin/bash testuser && \
    echo "testuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER testuser
WORKDIR /home/testuser

# Copy dotfiles
COPY --chown=testuser:testuser . .

# Remove default bash files so dotbot can link ours
RUN rm -f ~/.bash_profile ~/.bashrc

CMD ["/bin/bash", "--login"]
