#!/usr/bin/env bash

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
  height=34 \
  color=0x00000000 \
  margin=0 \
  sticky=on \
  padding_left=8 \
  padding_right=3 \
  notch_width=188 \
  display=main

# Alternative background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
  background.color=0x66494d64 \
  background.corner_radius=5 \
  background.padding_right=5 \
  background.height=26 \
  icon.font="$FONT_FACE:Medium:15.0" \
  icon.padding_left=5 \
  icon.padding_right=5 \
  label.font="$FONT_FACE:Medium:12.0" \
  label.color=0xffcad3f5 \
  label.y_offset=0 \
  label.padding_left=0 \
  label.padding_right=5

sketchybar --add item current_space left \
  --set current_space \
  background.color=0xffb7bdf8 \
  icon.color=0xff24273a \
  icon.font="$FONT_FACE:Bold:20.0" \
  icon.y_offset=1 \
  label.drawing=off \
  script="$PLUGIN_SHARED_DIR/current_space.sh" \
  --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
  --set front_app \
  background.color=0xffa6da95 \
  background.padding_left=0 \
  background.padding_right=0 \
  icon.y_offset=1 \
  icon.color=0xff24273a \
  label.drawing=no \
  script="$PLUGIN_SHARED_DIR/front_app.sh" \
  --add item front_app.separator left \
  --set front_app.separator \
  background.color=0x00000000 \
  background.padding_left=-3 \
  icon= \
  icon.color=0xffa6da95 \
  icon.font="$FONT_FACE:Bold:20.0" \
  icon.padding_left=0 \
  icon.padding_right=0 \
  icon.y_offset=1 \
  label.drawing=no \
  --add item front_app.name left \
  --set front_app.name \
  background.color=0x00000000 \
  background.padding_right=0 \
  icon.drawing=off \
  label.font="$FONT_FACE:Bold:12.0" \
  label.drawing=yes

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space."$sid" left \
    --subscribe space."$sid" aerospace_workspace_change \
    --set space."$sid" \
    background.color=0x44ffffff \
    background.corner_radius=5 \
    background.height=20 \
    background.drawing=off \
    background.padding_left=5 \
    label="$sid" \
    label.padding_right=8 \
    icon.padding_left=0 \
    click_script="aerospace workspace $sid" \
    script="$PLUGIN_SHARED_DIR/aerospace.sh $sid"
done

sketchybar --add bracket front_app_bracket \
  front_app \
  front_app.separator \
  front_app.name \
  --subscribe front_app front_app_switched

sketchybar --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify c \
  --set spotify \
  icon= \
  icon.y_offset=1 \
  icon.font="$FONT_FACE:Bold:20.0" \
  label.drawing=off \
  label.padding_left=3 \
  script="$PLUGIN_DIR/spotify.sh" \
  --subscribe spotify spotify_change mouse.clicked

sketchybar --add item clock right \
  --set clock \
  icon=󰃰 \
  icon.color=0xffb7bdf8 \
  label.font="$FONT_FACE:Normal:14.0" \
  update_freq=10 \
  script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
  --set battery \
  update_freq=30 \
  label.font="$FONT_FACE:Normal:14.0" \
  script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
  --set volume \
  icon.color=0xffb7bdf8 \
  label.drawing=true \
  label.font="$FONT_FACE:Normal:14.0" \
  script="$PLUGIN_SHARED_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --add item weather right \
  --set weather \
  background.padding_right=20 \
  icon= \
  icon.color=0xffb7bdf8 \
  icon.font="$FONT_FACE:Bold:16.0" \
  label.font="$FONT_FACE:Normal:14.0" \
  update_freq=900 \
  script="$PLUGIN_SHARED_DIR/weather.sh" \
  --subscribe weather system_woke

sketchybar --add item weather.moon right \
  --set weather.moon \
  icon.color=0xffb7bdf8 \
  icon.font="$FONT_FACE:Bold:22.0" \
  label.drawing=off \
  --subscribe weather.moon mouse.clicked

osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
