#!/usr/bin/env bash

# All I ever do is source ~/.bashrc; this ought to store our dots root path.
export DOTFILES_PATH="$(dirname $(dirname $(readlink "${BASH_SOURCE[0]}")))"

# Trying to adhere to the XDG Base Directory Specification.
source "$DOTFILES_PATH/config/xdg_paths"

# Load the mandatory shell settings and ENV vars before everything else.
[ -f $DOTFILES_PATH/bash/colors.sh ] && source "$DOTFILES_PATH/bash/colors.sh"
[ -f $DOTFILES_PATH/bash/helpers.sh ] && source "$DOTFILES_PATH/bash/helpers.sh"
[ -f $DOTFILES_PATH/bash/shell.sh ] && source "$DOTFILES_PATH/bash/shell.sh"

# Source the files in the bash folder
for file in $DOTFILES_PATH/bash/{aliases,prompt,private}.sh; do
  [ -r "$file" ] && source "$file";
done;
unset file;

# OS specific settings
#[[ $OS == 'windows' ]] && source "$DOTFILES_PATH/bash/wsl.sh"
#[[ $OS == 'macos' ]] && source "$DOTFILES_PATH/bash/macos.sh"
#[[ $OS == 'linux' ]] && source "$DOTFILES_PATH/bash/linux.sh"

# OS specific settings
case $($DOTFILES_PATH/bin/os) in
  windows) source "$DOTFILES_PATH/bash/wsl.sh";;
  macos) source "$DOTFILES_PATH/bash/macos.sh";;
  linux) source "$DOTFILES_PATH/bash/linux.sh";;
esac

export DOTFILES_SALT_PATH="$DOTFILES_DATA_PATH/salt.enc"
export DOTFILES_LOG_PATH="$DOTFILES_STATE_PATH/log"

