#!/bin/bash

# Reset global OS X settings
defaults delete -g NSAutomaticWindowAnimationsEnabled
defaults delete -g NSWindowResizeTime
defaults delete -g AppleEdgeResizeExteriorSize
defaults delete -g AppleMomentumScrollSupported
defaults -currentHost delete -g AppleFontSmoothing
defaults delete -g ApplePressAndHoldEnabled
defaults delete -g NSNavPanelExpandedStateForSaveMode

# Reset screencapture to default settings
defaults write com.apple.screencapture type -string PNG
defaults delete com.apple.screencapture disable-shadow

# Reset the Finder
rm ~/Library/Preferences/com.apple.finder.plist

# Reset the Dock
rm ~/Library/Preferences/com.apple.dock.plist

# Reset the dashboard
rm ~/Library/Preferences/com.apple.dashboard.plist

# Reset Desktop and Launch services
rm ~/Library/Preferences/com.apple.desktopservices.plist
rm ~/Library/Preferences/com.apple.launchservices.plist

# Turn on Time Machine
sudo tmutil enable

# Enable Notification Center
sudo defaults write /System/Library/LaunchAgents/com.apple.notificationcenterui KeepAlive -bool true
