#!/bin/bash
set -e

fail() {
  printf "%s\n" "$1" >&2
  exit "${2-1}"
}

source "$DOTFILES_REPO_HOME"/bash/env/xdg.sh
source "$DOTFILES_REPO_HOME"/bash/helpers.sh

# Get dotbot installed
dotbot_path="$DOTFILES_REPO_HOME/dotbot"
git -C "$dotbot_path" submodule sync --quiet --recursive
git -C "$dotbot_path" submodule update --init --recursive
git -C "$dotbot_path" submodule update --remote dotbot

# Activate dotbot with the install configuration
"$dotbot_path/bin/dotbot" -d "$DOTFILES_REPO_HOME" -c "$DOTFILES_REPO_HOME/setup/install.conf.yaml" "$@"

if [ ! -f "$DOTFILES_CONFIG_HOME/env" ]; then
  touch "$DOTFILES_CONFIG_HOME/env"
fi

echo
green "==> Apply changes by running \`source ${BASHRC/$HOME/~}\` to reload your shell."
