#!/usr/bin/env bash

# Default command overrides. Generally trying to avoid serious ones, but to
# my knowledge these are not considered harmful.
alias ls='ls -G'
alias nano='vim' # 😬
alias rsync='rsync --exclude-from=${HOME}/.rsyncignore'
alias vim=${EDITOR} # My usecase here is that I use `dvim` as my Neovim profile.
alias vi='vim'

# Shortcuts
alias be='bundle exec'
alias ds='du -sh */' # Short for "directory sizes"
alias fs="ls -laSh $1 | grep -v ^d | awk '{print $5 "\t" $9}'"
alias lsa='ls -hal'
alias mysqldump='mysqldump --set-gtid-purged=OFF' # MySQL 5.6 "global-transaction-error on dump"-fix
alias redis='brew services start redis'
alias s='source ${HOME}/.bashrc && echo "${HOME}/.bashrc sourced!"'
alias ta='tmux attach'

# Spelling corrections
# NOTE: `timesused <alias>` to find out how many times you made a mistake.
alias gti='git' 
alias sl='ls'

# Generic helpers and custom commands
alias bundle_mysql2_openssl_fix="bundle config --local build.mysql2 '--with-ldflags=-L${BREW_PATH}/opt/openssl/lib --with-cppflags=-I${BREW_PATH}/opt/openssl/include'"
alias colors='for i in {0..255} ; do printf "\x1b[38;5;${i}mcolour${i}\n"; done'
alias http='ruby -run -ehttpd . -p3000' # Run a quick & basic local HTTP server
alias mysql-largest-db-tables="mysql -e \"SELECT table_schema AS 'Database', table_name AS 'Table', round(((data_length + index_length) / 1024 / 1024), 2) 'Size in MB' FROM information_schema.TABLES WHERE table_schema NOT IN('sys','information_schema', 'performance_schema', 'mysql') AND round(((data_length + index_length) / 1024 / 1024), 2) >= 5 ORDER BY (data_length + index_length) DESC;\"" # TODO: Extract
alias mysql-docker='mysql -h localhost -P 3306 --protocol=tcp'
alias sar='search_and_replace' # TODO: Extract
alias trim="awk '{\$1=\$1;print}'" # Strip leading/trailing whitespace

# Custom executables in my dotfiles
alias d='${HOME}/.local/bin/tmux/d'
alias dotfiles='${HOME}/.local/bin/tmux/quickstart dotfiles'
alias dotvim='${HOME}/.local/bin/tmux/quickstart dotvim'
