#!/bin/bash

# This file will only load on Linux

# WARNING: This is highly subjective and highly experimental. I will update this
# file the moment I'm on Linux more frequently.

setxkbmap -option altwin:ctrl_win # Switch win/command key with ctrl
setxkbmap -option ctrl:nocaps # Switch capslock with ctrl

# Make sure we can use 256 color in (XFCE)Terminal
if [ -e /usr/share/terminfo/x/xterm-256color ] && [ "$COLORTERM" == "xfce4-terminal" ]; then
  export TERM=xterm-256color
fi

# Runs albert headless
# Project link: https://github.com/ManuelSchneid3r/albert
if [ ! `pgrep -n albert` ]; then
  nohup albert </dev/null &>/dev/null &
fi

alias pbcopy='xclip -selection clipboard'
