#!/bin/bash

# This file will only load on macos.

alias ss="osascript ~/.macos/hide-terminal.scpt && tss && killall Terminal"
alias allow='xattr -d com.apple.quarantine'
alias ls='ls -G'
alias lsa='ls -hal'
alias toggle_desktop='toggle_default finder CreateDesktop'
alias toggle_hidden_files='toggle_default finder AppleShowAllFiles'
alias tss='take_screenshot'

# iTerm2 shell integration
if [ ! -f ~/.bash/completions/iterm2_shell_integration.bash ]; then
  curl -L https://iterm2.com/shell_integration/bash \
    -o ~/.bash/completions/iterm2_shell_integration.bash
fi

# takes a screenshot and uploads it to my hosting
take_screenshot()
{
  filename="$(date +%Y-%m-%d-%H-%M-%S).jpg"

  # TODO: Configure the destination server with ENV vars or something.
  screencapture -ix ~/Desktop/$filename &&
    scp ~/Desktop/$filename davelens.be:screenshots/$filename
  echo "https://www.davelens.be/screenshots/$filename" | pbcopy
  rm ~/Desktop/$filename
}

# toggles a boolean setting in the com.apple environment
toggle_default()
{
  environment=$1
  setting=$2
  value="$(defaults read com.apple.$environment $setting)"

  if [[ $value == 0 ]]; then
    newValue="TRUE"
  else
    newValue="FALSE"
  fi

  defaults write com.apple.$environment $setting -bool $newValue
  killall Finder
  echo "$setting is now $newValue."
}

# Use quicklook in debug mode to quickly display file info.
quicklook()
{
  qlmanage -p $1 >& /dev/null
}
