#!/usr/bin/env bash

# This file will only load on macos.

alias ss="osascript ~/.macos/hide-terminal.scpt && screenshot && killall Terminal"
alias allow='xattr -d com.apple.quarantine'
alias ls='ls -G'
alias lsa='ls -hal'
alias toggle_desktop='toggle_default finder CreateDesktop'
alias toggle_hidden_files='toggle_default finder AppleShowAllFiles'

# iTerm2 shell integration
if [ ! -f ~/.bash/completions/iterm2_shell_integration.bash ]; then
  curl -L https://iterm2.com/shell_integration/bash \
    -o ~/.bash/completions/iterm2_shell_integration.bash
fi

# toggles a boolean setting in the com.apple environment
toggle_default()
{
  environment=$1
  setting=$2
  value="$(defaults read com.apple.$environment $setting)"

  if [[ $value == 0 ]]; then
    newValue="TRUE"
  else
    newValue="FALSE"
  fi

  defaults write com.apple.$environment $setting -bool $newValue
  killall Finder
  echo "$setting is now $newValue."
}

# Use quicklook in debug mode to quickly display file info.
quicklook()
{
  qlmanage -p $1 >& /dev/null
}
