#!/bin/bash

########################################################################
# OVERWRITE SHELL VARS
########################################################################

# list the directories we want to add to the PATH variable, if they exist.
paths_to_add=(
  "$HOME/bin"
  # RVM
  "$HOME/.rvm/bin"
  # MySQL
  /usr/local/mysql/bin
  # Homebrew
  /usr/local/{,s}bin
  # Macports
  /opt/local/{,s}bin
  # System
  /{,s}bin
  /usr/{,s}bin
  # Git
  /usr/local/git/bin
  # X binaries
  /usr/X11/bin
  # MAMP
  /Applications/MAMP/Library/bin
);


# Now implode everything into the new PATH variable.
printf -v PATH "%s:" "${paths_to_add[@]}";
export PATH="${PATH%:}";

# Load RVM (Ruby Version Manager) into a shell session as a function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# General settings
export EDITOR=vim
export CLICOLOR=1

# Prefer the Queen's English and use UTF-8.
export LC_ALL='en_GB.UTF-8';
export LC_CTYPE='en_GB.UTF-8';
export LANG='en_GB';

# don't put duplicate lines in the history
export HISTCONTROL=ignoredups

# let the history ignore the following commands
export HISTIGNORE="ls:ll:la:pwd:clear:h:j"

# PAGER is the path to the program used to list the contents of files through
export PAGER='less --quit-if-one-screen --no-init --ignore-case --RAW-CONTROL-CHARS --quiet --dumb';

# Vim plugin CommandT split-window fix; see http://groups.google.com/group/iterm2-discuss/browse_thread/thread/47700851d59386fb?pli=1
stty -ixon

########################################################################
# SHELL OPTIONS
########################################################################

# append to the history file rather than overwriting
shopt -s histappend
shopt -s nocaseglob;


