#!/bin/bash

########################################################################
# OVERWRITE SHELL VARS
########################################################################

# /usr/local binaries should always come first
if [[ $PATH != */usr/local* ]] ; then
	export PATH="/usr/local/bin:$PATH"
	export PATH="/usr/local/sbin:$PATH"
fi

# MAMP binaries
if [[ $PATH != */Applications/MAMP/Library/bin* ]] ; then
	export PATH="$PATH:/Applications/MAMP/Library/bin"
fi

# XCode X11 binaries
if [[ $PATH != */usr/X11/bin* ]] ; then
	export PATH="$PATH:/usr/X11/bin"
fi


# Load RVM (Ruby Version Manager) into a shell session as a function
[[ -s ~/.rvm/scripts/rvm ]] && . ~/.rvm/scripts/rvm

# General settings 
export EDITOR=vim
export CLICOLOR=1

# Prefer the Queen's English and use UTF-8.
export LC_ALL='en_GB.UTF-8';
export LANG='en_GB';

# don't put duplicate lines in the history
export HISTCONTROL=ignoredups 

# let the history ignore the following commands
export HISTIGNORE="ls:ll:la:pwd:clear:h:j"

# PAGER is the path to the program used to list the contents of files through
export PAGER='less --quit-if-one-screen --no-init --ignore-case --RAW-CONTROL-CHARS --quiet --dumb';

########################################################################
# SHELL OPTIONS
########################################################################

# append to the history file rather than overwriting
shopt -s histappend 
shopt -s nocaseglob;


