#!/bin/bash

########################################################################
# GENERAL
########################################################################
export EDITOR=vim

# Make ls & grep pretty
export CLICOLOR=1
export GREP_OPTIONS='--color=auto'

# PAGER is the path to the program used to list the contents of files through
export PAGER='less --quit-if-one-screen --no-init --ignore-case --RAW-CONTROL-CHARS --quiet --dumb';

# Stop checking shellmail for new messages
unset MAILCHECK

# Vim plugin CommandT split-window fix; see http://groups.google.com/group/iterm2-discuss/browse_thread/thread/47700851d59386fb?pli=1
stty -ixon


########################################################################
# PATH
########################################################################

# list the directories we want to add to the PATH variable, if they exist.
paths_to_add=(
  "$HOME/bin"
  # RVM
  "$HOME/.rvm/bin"
  "$HOME/.rvm/scripts/rvm"
  # MySQL
  /usr/local/mysql/bin
  # Homebrew
  /usr/local/{,s}bin
  # Macports
  /opt/local/{,s}bin
  # System
  /{,s}bin
  /usr/{,s}bin
  # Git
  /usr/local/git/bin
  # X binaries
  /usr/X11/bin
  # Firefox
  "$HOME/Applications/Firefox.app/Contents/MacOS"
  # PEAR
  /usr/local/Cellar/php53/5.3.25/bin
  # Node
  /usr/local/share/npm/bin
  # Dotfiles
  "$HOME/.dotfiles/bin"
);


# Now implode everything into the new PATH variable.
printf -v PATH "%s:" "${paths_to_add[@]}";
export PATH="${PATH%:}";

# RVM scripts loading
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# node.js modules path
export NODE_PATH="/usr/local/share/npm/lib/node_modules"

########################################################################
# HISTORY
########################################################################
# When the command contains an invalid history operation (for instance when
# using an unescaped "!" (I get that a lot in quick e-mails and commit
# messages) or a failed substitution (e.g. "^foo^bar" when there was no "foo"
# in the previous command line), do not throw away the command line, but let me
# correct it.
shopt -s histreedit;

# append to the history file rather than overwriting
shopt -s histappend

# Keep a reasonably long history.
export HISTSIZE=4096;

# Keep even more history lines inside the file, so we can still look up
# previous commands without needlessly cluttering the current shell's history.
export HISTFILESIZE=16384;

# When executing the same command twice or more in a row, only store it once.
export HISTCONTROL=ignoredups;

# Keep track of the time the commands were executed.
# The xterm colour escapes require special care when piping; e.g. "| less -R".
export HISTTIMEFORMAT="${FG_BLUE}${FONT_BOLD}%Y/%m/%d %H:%M:%S${FONT_RESET} ";

# let the history ignore the following commands
export HISTIGNORE="ls:ll:la:pwd:clear:h:j"


########################################################################
# LOCALE AND COMPLETION
########################################################################
# general case-insensitive globbing
shopt -s nocaseglob;

# do not autocomplete when accidentally pressing tab on an empty line.
shopt -s no_empty_cmd_completion;

# Do not overwrite files when redirecting using ">".
# Note that you can still override this with ">|".
set -o noclobber;

# prefer English and use UTF-8.
printf -v available_locales ' %s ' $(locale -a);
for lang in en_US en_GB en; do
	for locale in "$lang".{UTF-8,utf8}; do
		if [[ "$available_locales" =~ " $locale " ]]; then
			export LC_ALL="$locale";
			export LANG="$lang";
			break 2;
		fi;
	done;
done;
unset available_locales lang locale;
