#!/usr/bin/env bash

# This file will only load on WSL.

# di = directory
# fi = file
# ln = symbolic link
# pi = fifo file
# so = socket file
# bd = block (buffered) special file
# cd = character (unbuffered) special file
# or = symbolic link pointing to a non-existent file (orphan)
# mi = non-existent file pointed to by a symbolic link (visible when you type ls -l)
# ex = file which is executable (ie. has 'x' set in permissions).
# *.rpm = files with the ending .rpm
LS_COLORS=$LS_COLORS:'di=0;35:'; export LS_COLORS
alias lsa='ls -hal --color=tty'
alias pbcopy='clip.exe'

export LDFLAGS="-L${BREW_PATH}/opt/mysql@5.7/lib"
export CPPFLAGS="-I${BREW_PATH}/opt/mysql@5.7/include"
export PKG_CONFIG_PATH="${BREW_PATH}/opt/mysql@5.7/lib/pkgconfig"

# Start the SSH agent
eval "$(ssh-agent -s >/dev/null)"

# After an upgrade to Ubuntu 20.04 LTS, brew no longer gets loaded by default.
eval $(SHELL=/bin/bash /home/linuxbrew/.linuxbrew/bin/brew shellenv)
