ask_questions() {
  read -rp "GitHub username: " GITHUB_USERNAME
  read -rp "GitHub email: " GITHUB_EMAIL
  read -rsp "GitHub personal access token: " GITHUB_PERSONAL_ACCESS_TOKEN
  echo
  echo
}

bw_github() {
  bw list items --search "GitHub" --session "$(bw_session)"
}

bw_session() {
  if [ "$(bw status | jq '.status')" == '"unauthenticated"' ]; then
    BW_SESSION=$(bw login --raw)
  fi

  if [ -z "$BW_SESSION" ]; then
    BW_SESSION=$(bw unlock --raw)
    export BW_SESSION
  fi

  echo "$BW_SESSION"
}

use_bitwarden() {
  ! command -v bw >/dev/null && brew install bitwarden-cli

  github_data="$(bw_github)"
  GITHUB_PERSONAL_ACCESS_TOKEN=$(echo "$github_data" | jq -r '.[].fields | map(select(.name == "Personal access token"))[0].value')
  GITHUB_USERNAME=$(echo "$github_data" | jq -r '.[].fields | map(select(.name == "Public username"))[0].value')
  GITHUB_EMAIL=$(echo "$github_data" | jq -r '.[].login.username')
}

write_dots_env_file() {
  local env_file="$DOTFILES_CONFIG_HOME/env"

  echo "# Generated by my dotfiles' install script on $(date)" >"$env_file"

  declare -p \
    REPO_NAMESPACE \
    DOTFILES_REPO_HOME \
    GITHUB_EMAIL \
    GITHUB_USERNAME \
    GITHUB_PERSONAL_ACCESS_TOKEN \
    GITHUB_SIGNING_KEY |
    sed 's/declare -[-x] //g' >>"$env_file"
}

write_gitconfig_env_file() {
  local env_file="$XDG_CONFIG_HOME/git/config.env"
  local template_file="$DOTFILES_REPO_HOME/setup/gitconfig.env.template"

  echo "# Generated by my dotfiles' install script on $(date)" >"$env_file"

  content=$(envsubst <"$template_file")
  echo "$content" >>"$env_file"
}

main() {
  if macos; then
    use_bitwarden
  else
    ask_questions
  fi

  [ -f "$HOME"/.ssh/id_rsa.pub ] && GITHUB_SIGNING_KEY="$HOME/.ssh/id_rsa.pub"

  export GITHUB_EMAIL
  export GITHUB_USERNAME
  export GITHUB_PERSONAL_ACCESS_TOKEN
  export GITHUB_SIGNING_KEY

  write_dots_env_file
  write_gitconfig_env_file
}

save_cursor

echo
echo "4. $(underline "CONFIGURE ENVIRONMENT")"
echo

main "$@"

# shellcheck disable=SC2181
if [ $? -eq 0 ]; then
  # TODO: Enable when the step is done.
  # reset_prompt
  echo "✓ $(fgreen "Environment configured! Remember to use $(black "dots update")")$(fgreen " once in a while")"
else
  fail "x $(fred "Something went wrong during step 4.")"
fi
