ask_questions() {
  read -rp "GitHub username: " GITHUB_USERNAME </dev/tty
  read -rp "GitHub email: " GITHUB_EMAIL </dev/tty
  read -rp "GitHub personal access token: " GITHUB_PERSONAL_ACCESS_TOKEN </dev/tty
  read -rsp "Claude Code OAuth token: " CLAUDE_CODE_OAUTH_TOKEN </dev/tty
  echo
  echo
}

bw_search() {
  bw list items --search "$1" --session "$BW_SESSION"
}

bw_unlock() {
  local status
  status="$(bw status | jq -r '.status')"

  if [ "$status" = "unauthenticated" ]; then
    echo "Bitwarden requires authentication. Please enter your master password." >&2
    BW_SESSION=$(bw login --raw </dev/tty)
  elif [ "$status" = "locked" ]; then
    echo "Bitwarden vault is locked. Please enter your master password." >&2
    BW_SESSION=$(bw unlock --raw </dev/tty)
  fi

  export BW_SESSION
}

use_bitwarden() {
  export NODE_OPTIONS="--no-deprecation"

  # Establish session once upfront
  bw_unlock

  github_data="$(bw_search "GitHub")"
  GITHUB_PERSONAL_ACCESS_TOKEN=$(echo "$github_data" | jq -r '.[].fields | map(select(.name == "Personal access token"))[0].value')
  GITHUB_USERNAME=$(echo "$github_data" | jq -r '.[].fields | map(select(.name == "Public username"))[0].value')
  GITHUB_EMAIL=$(echo "$github_data" | jq -r '.[].login.username')

  anthropic_data="$(bw_search "Anthropic")"
  CLAUDE_CODE_OAUTH_TOKEN=$(echo "$anthropic_data" | jq -r '.[].fields | map(select(.name == "CLAUDE_CODE_OAUTH_TOKEN"))[0].value')
}

write_dots_env_file() {
  local env_file="$DOTFILES_CONFIG_HOME/env"

  echo "# Generated by my dotfiles' install script on $(date)" >"$env_file"

  declare -p \
    REPO_NAMESPACE \
    DOTFILES_REPO_HOME \
    GITHUB_EMAIL \
    GITHUB_USERNAME \
    GITHUB_PERSONAL_ACCESS_TOKEN \
    GITHUB_SIGNING_KEY \
    CLAUDE_CODE_OAUTH_TOKEN |
    sed 's/declare -[-x] /export /g' >>"$env_file"
}

write_gitconfig_env_file() {
  local env_file="$XDG_CONFIG_HOME/git/config.env"
  local template_file="$DOTFILES_REPO_HOME/setup/git/gitconfig.env.template"

  echo "# Generated by my dotfiles' install script on $(date)" >"$env_file"

  content=$(envsubst <"$template_file")
  echo "$content" >>"$env_file"
}

try_bitwarden() {
  local bw_failed=0

  # Temporarily swap the interrupt handler so ctrl+c during bitwarden
  # just marks it as failed instead of tearing down the entire installer.
  trap 'bw_failed=1' SIGINT

  if ! use_bitwarden; then
    bw_failed=1
  fi

  # Restore the original interrupt handler
  trap 'interrupt_handler' SIGINT

  if [ "$bw_failed" = "1" ]; then
    echo
    echo -e "$(fyellow "Bitwarden failed. Falling back to manual input.")"
    echo
    ask_questions
  fi
}

main() {
  if command -v bw >/dev/null; then
    try_bitwarden
  else
    ask_questions
  fi

  [ -f "$HOME"/.ssh/id_rsa.pub ] && GITHUB_SIGNING_KEY="$HOME/.ssh/id_rsa.pub"

  export GITHUB_EMAIL
  export GITHUB_USERNAME
  export GITHUB_PERSONAL_ACCESS_TOKEN
  export GITHUB_SIGNING_KEY
  export CLAUDE_CODE_OAUTH_TOKEN

  write_dots_env_file
  write_gitconfig_env_file
}

echo "4. $(underline "CONFIGURE ENVIRONMENT")"
echo

if main "$@"; then
  report_step "✓ $(fgreen "Environment configured! Remember to use $(black "dots update")")$(fgreen " once in a while")"
  show_progress
else
  fail "x $(fred "Something went wrong during step 4.")"
fi
