[env]
LUAROCKS_VERSION = "3.11.1"
ASDF_LUA_LUAROCKS_VERSION = "3.11.1"
RUBY_CONFIGURE_OPTS = "--enable-zjit"

[tools]
elixir = "1.19.5"
elixir-ls = "latest"
erlang = "28.4.1"
golang = "latest"
lua-language-server = "3.18.2"
neovim = "0.12.1"
nodejs = "25.9.0"
postgres = "18.1"
ruby = "3.4.8"
rust = "1.95.0"
shellcheck = "0.11.0"
shfmt = "3.13.1"
stylua = "2.4.1"
usage = "latest"
yarn = "4.12.0"

[settings]

[settings.ruby]
compile = false
