[env]
LUAROCKS_VERSION = "3.11.1"
ASDF_LUA_LUAROCKS_VERSION = "3.11.1"
RUBY_CONFIGURE_OPTS = "--enable-zjit"

[tools]
claude-code = "2.1.234"
elixir = "1.20.3"
elixir-ls = "latest"
erlang = "29.0.5"
golang = "latest"
lua-language-server = "3.19.1"
neovim = "0.12.3"
nodejs = "26.7.0"
opencode = "1.18.18"
postgres = "18.6"
ruby = "3.4.9"
rust = "1.97.1"
shellcheck = "0.11.0"
shfmt = "3.13.1"
stylua = "2.5.2"
usage = "latest"
yarn = "4.18.0"

[settings]

[settings.ruby]
compile = false
